### ISSUE TITLE
我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59

### ISSUE THREAD

**Issue by liujianghao1023** [HUSTSYJ/DA_dahazing#14]

**Comment by Four97** [comment]
gpu_id改一下试试

**Comment by liujianghao1023** [comment]
好的&nbsp; 我马上去试&nbsp; 万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HUSTSYJ/DA_dahazing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 下午3:31
收件人:&nbsp;"HUSTSYJ/DA_dahazing"<DA_dahazing@noreply.github.com&gt;;
抄送:&nbsp;"15465545645"<582379270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HUSTSYJ/DA_dahazing] 我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59 (#14)





 
gpu_id改一下试试

**Comment by liujianghao1023** [comment]
在初始传参数 中设置了gup id 0 然后出现了&nbsp; 由于目标计算机积极绝&nbsp; 无法连接&nbsp; 我在csdn上查了 重新设置代理网&nbsp; 也不行&nbsp; 所以又来求助了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Four97"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午3:31
收件人: "HUSTSYJ/DA_dahazing"<DA_dahazing@noreply.github.com&gt;; 
抄送: "15465545645"<582379270@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HUSTSYJ/DA_dahazing] 我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59 (#14)





 
gpu_id改一下试试

**Comment by liujianghao1023** [comment]
我的qq582379270

**Comment by Liu-MeiLi1** [comment]
解决了吗  cmd 输入python -m visdom.server 激活visdom 然后打开cmd输出的网址（http://localhost:8097  就能在这个网页页面上实现可视化了  再输命令跑程序就不会报错了

**Comment by liujianghao1023** [comment]
解决了 谢谢 跑出来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HUSTSYJ/DA_dahazing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 下午4:40
收件人:&nbsp;"HUSTSYJ/DA_dahazing"<DA_dahazing@noreply.github.com&gt;;
抄送:&nbsp;"15465545645"<582379270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HUSTSYJ/DA_dahazing] 我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59 (#14)





 
解决了吗  cmd 输入python -m visdom.server 激活visdom 然后打开cmd输出的网址（http://localhost:8097  就能在这个网页页面上实现可视化了  再输命令跑程序就不会报错了

**Comment by Liu-MeiLi1** [comment]
啊我在train第二个部分 也就是Fr部分的时候&nbsp; 输入训练命令“model RDehazingnet --g_s2r_premodel ./checkpoints/run_cyclegan/netG_A.pth&nbsp; ”&nbsp;&nbsp;&nbsp; 会报错找不到文件“ [Errno 2] No such file or directory: './checkpoints/run_cyclegan/netG_A.pth'
” 你出现这个问题了吗&nbsp; 以及是怎么解决的呀 跪谢orz




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HUSTSYJ/DA_dahazing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 下午4:42
收件人:&nbsp;"HUSTSYJ/DA_dahazing"<DA_dahazing@noreply.github.com&gt;;
抄送:&nbsp;"刘香茹"<250747286@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [HUSTSYJ/DA_dahazing] 我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59 (#14)





 解决了 谢谢 跑出来了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "HUSTSYJ/DA_dahazing"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年11月24日(星期二) 下午4:40 
 收件人:&amp;nbsp;"HUSTSYJ/DA_dahazing"<DA_dahazing@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"15465545645"<582379270@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [HUSTSYJ/DA_dahazing] 我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59 (#14) 
 
 
 
 
 
   
 解决了吗  cmd 输入python -m visdom.server 激活visdom 然后打开cmd输出的网址（http://localhost:8097  就能在这个网页页面上实现可视化了  再输命令跑程序就不会报错了

**Comment by liujianghao1023** [comment]
我记得好像要么自己建立文件&nbsp; 要么他训练的网格是错的 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HUSTSYJ/DA_dahazing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 下午4:47
收件人:&nbsp;"HUSTSYJ/DA_dahazing"<DA_dahazing@noreply.github.com&gt;;
抄送:&nbsp;"15465545645"<582379270@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HUSTSYJ/DA_dahazing] 我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59 (#14)





 啊我在train第二个部分 也就是Fr部分的时候&amp;nbsp; 输入训练命令“model RDehazingnet --g_s2r_premodel ./checkpoints/run_cyclegan/netG_A.pth&amp;nbsp; ”&amp;nbsp;&amp;nbsp;&amp;nbsp; 会报错找不到文件“ [Errno 2] No such file or directory: './checkpoints/run_cyclegan/netG_A.pth' 
 ” 你出现这个问题了吗&amp;nbsp; 以及是怎么解决的呀 跪谢orz 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "HUSTSYJ/DA_dahazing"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年11月24日(星期二) 下午4:42 
 收件人:&amp;nbsp;"HUSTSYJ/DA_dahazing"<DA_dahazing@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"刘香茹"<250747286@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [HUSTSYJ/DA_dahazing] 我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59 (#14) 
 
 
 
 
 
  解决了 谢谢 跑出来了  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "HUSTSYJ/DA_dahazing"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年11月24日(星期二) 下午4:40  
  收件人:&amp;amp;nbsp;"HUSTSYJ/DA_dahazing"<DA_dahazing@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"15465545645"<582379270@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [HUSTSYJ/DA_dahazing] 我的问题RuntimeError: cuda runtime error (101) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59 (#14)  
   
   
   
   
   
     
  解决了吗  cmd 输入python -m visdom.server 激活visdom 然后打开cmd输出的网址（http://localhost:8097  就能在这个网页页面上实现可视化了  再输命令跑程序就不会报错了

**Comment by hlliu2021** [comment]
同学您好，能详细说下具体的步骤嘛，非常感谢
